import './global.css';
import ConvexClientProvider from './ConvexClientProvider';

export const metadata = {
  title: 'Welcome to my-new-app',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <ConvexClientProvider>{children}</ConvexClientProvider>
      </body>
    </html>
  );
}
